# 03 - First Multi-Layer Perceptron (MLP)

## 🎯 Objective

Build and train a simple Multi-Layer Perceptron (MLP) using PyTorch.

### Topics Covered

- Creating a neural network with `nn.Module`
- Fully connected (`nn.Linear`) layers
- Activation functions
- Loss function
- Optimizer
- Forward pass
- Backpropagation
- Training loop

## Theory

A Multi-Layer Perceptron (MLP) is one of the simplest types of artificial neural networks.

It consists of:
- An input layer
- One or more hidden layers
- An output layer

Each neuron in one layer is connected to every neuron in the next layer, which is why it is also called a **Fully Connected Neural Network**.

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
# Input data
X = torch.tensor([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
])

# Target labels
y = torch.tensor([
    [0.],
    [1.],
    [1.],
    [0.]
])

## Define the MLP Model

In PyTorch, neural networks are created by defining a class that inherits from `nn.Module`.

The model consists of:

- An input layer
- A hidden layer with ReLU activation
- An output layer

This architecture is called a **Multi-Layer Perceptron (MLP)**

In [3]:
class SimpleMLP(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(2, 4)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(4, 1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

In [4]:
# Create the model

model = SimpleMLP()

print(model)

SimpleMLP(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=4, out_features=1, bias=True)
)


## Define the Loss Function and Optimizer

Before training the model, we need:

- **Loss Function**: Measures how far the model's predictions are from the true values.
- **Optimizer**: Updates the model's parameters to reduce the loss.

In [5]:
# Loss Function
criterion = nn.BCEWithLogitsLoss()

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=0.1)

## Train the Model

The training loop performs the following steps repeatedly:

1. Make predictions (Forward Pass)
2. Compute the loss
3. Calculate gradients (Backward Pass)
4. Update model weights
5. Clear old gradients

In [6]:
# Training Loop

epochs = 1000

for epoch in range(epochs):

    # Forward pass
    outputs = model(X)

    # Calculate loss
    loss = criterion(outputs, y)

    # Clear previous gradients
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update weights
    optimizer.step()

    # Print loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Epoch [100/1000], Loss: 0.6908
Epoch [200/1000], Loss: 0.6682
Epoch [300/1000], Loss: 0.5861
Epoch [400/1000], Loss: 0.5021
Epoch [500/1000], Loss: 0.3900
Epoch [600/1000], Loss: 0.2051
Epoch [700/1000], Loss: 0.1146
Epoch [800/1000], Loss: 0.0767
Epoch [900/1000], Loss: 0.0563
Epoch [1000/1000], Loss: 0.0441


## Evaluate the Model

After training, we can use the trained model to make predictions on the input data.

In [7]:
# Disable gradient calculation during evaluation
with torch.no_grad():

    outputs = model(X)

    # Convert logits to probabilities
    predictions = torch.sigmoid(outputs)

    print(predictions)

tensor([[0.0650],
        [0.9780],
        [0.9808],
        [0.0654]])


In [8]:
# Convert probabilities to class labels

predicted_classes = (predictions >= 0.5).float()

print(predicted_classes)
print("Actual Labels:")
print(y)

tensor([[0.],
        [1.],
        [1.],
        [0.]])
Actual Labels:
tensor([[0.],
        [1.],
        [1.],
        [0.]])


## Conclusion

In this notebook, we built and trained our first Multi-Layer Perceptron (MLP) using PyTorch.

We learned how to:

- Define a neural network using `nn.Module`
- Use fully connected (`nn.Linear`) layers
- Choose an appropriate loss function
- Configure an optimizer
- Train the model using forward and backward passes
- Make predictions with the trained model

This notebook introduces the complete deep learning workflow that will be reused in future models such as CNNs, RNNs, and Transformers.